---
title: "opportunity_insights"
author: "Amy Tan"
date: "2/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(foreign)
library(haven)
library(dplyr)
library(tibble)
library(stringr)
library(fs)
library(devtools)
library(ggthemr)
library(cowplot)
library(stargazer)
library(tidyverse)



```

```{r}

# all_outcomes <- read.csv("raw-data/county_outcomes.csv")

# all_outcomes %>% glimpse()

# all_outcome data is too big so using different dataset instead for only
# household income and incarceration rates

download.file("https://opportunityinsights.org/wp-content/uploads/2018/10/county_outcomes_simple.csv", "raw-data/county_outcomes_simple.csv", mode="wb")

oi_county_outcomes <- read.csv("raw-data/county_outcomes_simple.csv")

# the county variable was a factor variable instead of a numeric variable, so I made # it numeric to match the county variable in the other dataset

oi_county_outcomes$county_num <- as.numeric(oi_county_outcomes %>% pull(county))

# also made the state variables numeric because I will need to merge the state and county IDs to match the five-digit FIPS county code in the stanford dataset

oi_county_outcomes$state_num <- as.numeric(oi_county_outcomes %>% pull(state))

# since the 5-digit FIPS code is formatted such that if there was a county code that # was less than 3 digits, there would be a 0 in front of it, I added 0s to county_num

oi_county_outcomes <- oi_county_outcomes %>% 
  mutate(county_pad=str_pad(county_num, 3, pad="0","left"))

# I used paste0 to merge the county and state together into one countyid to match the countyid in the other dataset

oi_county_outcomes$countyid <- paste0(oi_county_outcomes$state_num, oi_county_outcomes$county_pad)

# I also made sure that the merged column was numeric to merge with other datasets later

oi_county_outcomes$countyid <- as.numeric(oi_county_outcomes %>% pull(countyid))

```


```{r}
download.file("https://stacks.stanford.edu/file/druid:db586ns4974/seda_county_poolsub_cs_v30.csv", "raw-data/seda_county_poolsub_cs.csv", mode="wb")

# does not have grade or year (use original long dataset instead if necessary),
# but has scores, average learning rate, and trend in average test scores

county_poolsub <- read.csv("raw-data/seda_county_poolsub_cs.csv")

```

```{r }
# covariate data on SES variables 

download.file("https://stacks.stanford.edu/file/druid:db586ns4974/SEDA_cov_county_pool_v30.csv", "raw-data/seda_cov_county_pool.csv", mode="wb")

seda_cov <- read.csv("raw-data/seda_cov_county_pool.csv")

# more detailed data on racial achievement gaps

download.file("https://stacks.stanford.edu/file/druid:db586ns4974/seda_county_long_cs_v30.csv", "raw-data/seda_county_long.csv", mode="wb")

seda_long <- read.csv("raw-data/seda_county_long.csv")


```

```{r}
# merging data together

# smaller dataset by only covariates, not the full long test score data from SEDA
seda_oi_cov <- full_join(county_poolsub, seda_cov, by="countyid") %>% 
  full_join(., oi_county_outcomes, by = "countyid")

# all SEDA data in one dataset
seda_cov_joined <-full_join(county_poolsub, seda_cov, by="countyid") %>% 
  full_join(., seda_long, by = "countyid")

# SEDA long test score data and covariates datasets only
seda_scores_cov <- full_join(seda_long, seda_cov, by = "countyid")
  
# full dataset
seda_oi <- full_join(county_poolsub, seda_cov, by="countyid") %>% 
  full_join(., seda_long, by = "countyid") %>% 
  full_join(., oi_county_outcomes, by = "countyid")

# full dataset = seda_oi

#seda_oi <- full_join(seda_full, oi_county_outcomes, by="countyid")
```

```{r}

# regressions on intergenerational mobility and avg test scores

# right now, test scores are still significant with all these controls 

kfr_avg_math = lm(kfr_pooled_pooled_p25 ~ mn_avg_mth_ol + rswhtblk + rswhthsp + rsecdnec, data = seda_oi_cov)

# when you add the composite SES score, the significance of test scores go away

kfr_avg_math_1 = lm(kfr_pooled_pooled_p25 ~ mn_avg_mth_ol + rswhtblk + rswhthsp + rsecdnec + sesavgall, data = seda_oi_cov)

kfr_avg_math_2 = lm(kfr_pooled_pooled_p25 ~ mn_avg_mth_ol + rswhtblk + rswhthsp + rsecdnec + sesavgall + perblk + perhsp + perecd + sesavgwhtblk + sesavgwhthsp, data = seda_oi_cov)

summary(kfr_avg_math)
summary(kfr_avg_math_1)

# do the exact same thing with ELA

kfr_avg_ela = lm(kfr_pooled_pooled_p25 ~ mn_avg_ela_ol + rswhtblk + rswhthsp + rsecdnec, data = seda_oi_cov)

kfr_avg_ela_1 = lm(kfr_pooled_pooled_p25 ~ mn_avg_ela_ol + rswhtblk + rswhthsp + rsecdnec + sesavgall, data = seda_oi_cov)

kfr_avg_ela_2 =  lm(kfr_pooled_pooled_p25 ~ mn_avg_ela_ol + rswhtblk + rswhthsp + rsecdnec + sesavgall + perblk + perhsp + perecd + sesavgwhtblk + sesavgwhthsp, data = seda_oi_cov)

summary(kfr_avg_ela)

# interesting result because for ELA (and NOT math), test scores are still
# significant for intergenerational mobility regardless of SES + race

summary(kfr_avg_ela_1)

```

```{r}
# regression table for average test scores by subject on intergenerational mobility

stargazer(kfr_avg_math, kfr_avg_math_1, kfr_avg_math_2, kfr_avg_ela, kfr_avg_ela_1, kfr_avg_ela_2,
          type="html", 
          dep.var.labels=c("Intergenerational Mobility"),
          covariate.labels=c("Standardized Mean Math Score", "Standardized Mean ELA Score", "Relative Diversity index between schools: White/Black", "Relative Diversity index between schools: White/Hispanic", "Relative Diversity index between schools: Economically disadvantaged/Non ECD","SES Composite Score", "Percent Blacks in the Grade", "Percent Hispanic in the Grade", "Percent Economically Disadvantaged in the Grade", "White-Black Gap in SES Composite Score", "White-Hispanic Gap in SES Composite Score"),
          column.labels = c("Without Controls", "With SES Composite", "With Additional Controls", "Without Controls","With SES Composite", "With Additional Controls"), out="kfr_avg_math_ela.html")

```

```{r}

# maybe customize if have time: 
# ggthemr("fresh") 
# ggthemr_reset()

# plot of intergenerational mobility and avg test scores
# added county size as size of bubbles, then hid legend to be able to see data more clearly

mob_avg_ela_plot <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  ggplot(aes(x=mn_avg_ela_ol, y= kfr_pooled_pooled_p25, size= tot_asmts_ela)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(x = "Mean ELA Score",
       y = "Intergenerational Mobility (P25)") +
  theme_bw() +
  guides(size = FALSE)

# took out titles for the cowplot
# title = "Intergenerational Mobility and ELA Test Scores",
#        subtitle = "National Data on 3rd-8th graders, 2008-2016",
#        caption = "Data from Opportunity Insights and Stanford Education Data Archive.",

ggsave(mob_avg_ela_plot, file = "mob_avg_ela_plot.png")

mob_avg_math_plot <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  ggplot(aes(x=mn_avg_mth_ol, y= kfr_pooled_pooled_p25, size= tot_asmts_mth)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(x = "Mean Math Score",
       y = "Intergenerational Mobility (P25)") +
  theme_bw() +
  guides(size = FALSE)

ggsave(file = "mob_avg_mth_plot.png")

# kinda ugly when it's two panels, so maybe unnecessary?

mob_test_by_subject <- plot_grid(mob_avg_math_plot, mob_avg_ela_plot, 
  label_size = 5,
  label_x = 0, label_y = 0,
  hjust = -0.5, vjust = -0.5,
  rel_heights = c(6,6)
  )

ggsave("mob_test_by_subject.png")

# diversity measures by intergen mob

# black-white relative diversity index

mob_rswhtblk_all <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  ggplot(aes(x=rswhtblk, y= kfr_pooled_pooled_p25)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(x = "Black-White Diversity Index",
       y = "Intergenerational Mobility (P25)") +
  theme_bw()

ggsave("mob_rswhtblk_all.png")

mob_rswhtblk_blk <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  ggplot(aes(x=rswhtblk, y= kfr_black_pooled_p25)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(x = "Black-White Diversity Index",
       y = "Intergenerational Mobility for Blacks (P25)") +
  theme_bw()

ggsave("mob_rswhtblk_blk.png")

mob_rswhtblk_wht <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  ggplot(aes(x=rswhtblk, y= kfr_white_pooled_p25)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(x = "Black-White Diversity Index",
       y = "Intergenerational Mobility for Whites (P25)") +
  theme_bw()

ggsave("mob_rswhtblk_wht.png")

# ECD/non-ECD v. intergen mob plots

mob_rsecdnec_all <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  ggplot(aes(x=rsecdnec, y= kfr_pooled_pooled_p25)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(x = "ECD/Non-ECD Diversity Index",
       y = "Intergenerational Mobility (P25)") +
  theme_bw()

ggsave("mob_rsecdnec_all.png")

mob_rsecdnec_blk <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  ggplot(aes(x=rsecdnec, y= kfr_black_pooled_p25)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(x = "ECD/Non-ECD Diversity Index",
       y = "Intergenerational Mobility for Blacks (P25)") +
  theme_bw()

ggsave("mob_rsecdnec_blk.png")

mob_rsecdnec_wht <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  ggplot(aes(x=rsecdnec, y= kfr_white_pooled_p25)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(x = "ECD/Non-ECD Diversity Index",
       y = "Intergenerational Mobility for Whites (P25)") +
  theme_bw()

ggsave("mob_rsecdnec_wht.png")
```

```{r}
# plots of intergenerational mobility rates with different percentage of economically disadvantaged students

# subsetting the data
perecd_25 <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  filter(perecd <= .25) %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= kfr_pooled_pooled_p25, size= tot_asmts_mth)) +
  geom_point(alpha=.5) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(x = "Mean Standardized Math Score",
       y = "Intergenerational Mobility") +
  theme_bw()


perecd_50 <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  filter(perecd <=.50 & perecd >.25) %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= kfr_pooled_pooled_p25)) +
  geom_point(alpha=.5) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(x = "Mean Standardized Math Score",
       y = "Intergenerational Mobility") +
  theme_bw()  

perecd_75 <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  filter(perecd <=.75 & perecd >.5) %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= kfr_pooled_pooled_p25)) +
  geom_point(alpha=.5) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(x = "Mean Standardized Math Score",
       y = "Intergenerational Mobility") +
  theme_bw()  

perecd_100 <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  filter(perecd <=1.00 & perecd >.75) %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= kfr_pooled_pooled_p25),
         size = ) +
  geom_point(alpha=.5) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(x = "Mean Standardized Math Score",
       y = "Intergenerational Mobility") +
  theme_bw()  

# title = "Intergenerational Mobility and ELA Test Scores",
#        subtitle = "National Data on 3rd-8th graders, 2008-2016",
#        caption = "Data from Opportunity Insights and Stanford Education Data Archive.",

perecd_comb <- plot_grid(perecd_25, perecd_50, perecd_75, perecd_100, labels = c("0 to 25% ECD", "25% to 50% ECD", "50% to 75% ECD", "75% to 100% ECD"), 
  label_size = 5,
  label_x = 0, label_y = 0,
  hjust = -0.5, vjust = -0.5)

# saved this plot as perecd_mob_Rplot.png

# looking at how diversity and mean scores vary by level of poverty in school 

perecd_25_wb <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  filter(perecd <= .25) %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhtblk)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "Black-White Relative Diversity",
       cex.axis = 1.5) +
  theme_bw()

perecd_50_wb <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  filter(perecd <=.50 & perecd >.25) %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhtblk)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "Black-White Relative Diversity",
       cex.axis = 1.5) +
  theme_bw()  

perecd_75_wb <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  filter(perecd <=.75 & perecd >.5) %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhtblk)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "Black-White Relative Diversity",
       cex.axis = 1.5) +
  theme_bw()  

perecd_100_wb <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  filter(perecd <=1.00 & perecd >.75) %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhtblk)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "Black-White Relative Diversity",
       cex.axis = 1.5) +
  theme_bw()  

# title = "Intergenerational Mobility and ELA Test Scores",
#        subtitle = "National Data on 3rd-8th graders, 2008-2016",
#        caption = "Data from Opportunity Insights and Stanford Education Data Archive.",

perecd_wb_comb <- plot_grid(perecd_25_wb, perecd_50_wb, perecd_75_wb, perecd_100_wb, labels = c("0 to 25% ECD", "25% to 50% ECD", "50% to 75% ECD", "75% to 100% ECD"), 
  label_size = 5,
  label_x = 0, label_y = 0,
  hjust = -0.5, vjust = -0.5,
  rel_heights = c(6,6)
  )

ggsave("perecd_wb_comb.png")

```

```{r}

# do the same but breaking it down using poverty rate of the county

pov_25_wb <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  filter(povertyavgall <= .25) %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhtblk)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "Black-White Relative Diversity",
       cex.axis = 1.5) +
  theme_bw()

pov_50_wb <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  filter(povertyavgall <=.50 & povertyavgall >.25) %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhtblk)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "Black-White Relative Diversity",
       cex.axis = 1.5) +
  theme_bw()  

pov_75_wb <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  filter(povertyavgall <=.75 & povertyavgall >.5) %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhtblk)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "Black-White Relative Diversity",
       cex.axis = 1.5) +
  theme_bw()  

pov_100_wb <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  filter(povertyavgall <=1.00 & povertyavgall >.75) %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhtblk)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "Black-White Relative Diversity",
       cex.axis = 1.5) +
  theme_bw()  

# poverty rates ranged from .033 to .489, so only have two panels for the combined plot
seda_cov %>% select(countyid, povertyavgall) %>% arrange(desc(povertyavgall)) %>% head(10)
seda_cov %>% select(countyid, povertyavgall) %>% arrange(desc(povertyavgall)) %>% tail(10)

pov_wb_comb <- plot_grid(pov_25_wb, pov_50_wb, labels = c("0 to 25% Poverty Rate", "25% to 50% Poverty Rate"), 
  label_size = 5,
  label_x = 0, label_y = 0,
  hjust = -0.5, vjust = -0.5,
  rel_heights = c(6,6)
  )

ggsave("pov_wb_comb.png")

# a different visualization: seeing the size of points as the poverty rate, setting legend = FALSE 
# because it looks like blue rectangles with geom_smooth

pov_wb_bubble <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhtblk, size = povertyavgall)) +
  geom_point(alpha=.25) + 
  # geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "Black-White Relative Diversity",
       cex.axis = 1.5) +
  theme_bw() + 
  geom_smooth(method = lm, se = TRUE) +
  guides(size = FALSE)

ggsave("pov_wb_bubble.png")

# setting colors as racial group (maybe use ECD/non-ECD diversity index instead)
pov_wb_race <- seda_oi_cov %>% 
  filter(subgroup == "asn" | subgroup == "blk" | subgroup == "hsp" | subgroup == "wht") %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhtblk, color= subgroup)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "Black-White Relative Diversity",
       cex.axis = 1.5) +
  theme_bw()

ggsave("pov_wb_race.png")


```
```{r}

# seeing how ECD diversity varies by race
rsecdnec_race_plot <- seda_oi_cov %>% 
  filter(subgroup == "asn" | subgroup == "blk" | subgroup == "hsp" | subgroup == "wht") %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rsecdnec, size = tot_asmts_mth)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "ECD/Non-ECD Relative Diversity",
       cex.axis = 1.5) +
  theme_bw() +
  facet_wrap(~subgroup) + 
  guides(size = FALSE)

ggsave("resecdnec_race_plot.png")

# seeing how concentration of school ECD's effect on test scores varies by race

perecd_race_plot <- seda_oi_cov %>% 
  filter(subgroup == "asn" | subgroup == "blk" | subgroup == "hsp" | subgroup == "wht") %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= perecd, size = tot_asmts_mth)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "Percent of ECD Students",
       cex.axis = 1.5) +
  theme_bw() +
  facet_wrap(~subgroup) + 
  guides(size = FALSE)

ggsave("perecd_race_plot.png")

# seeing how concentration of ECD students on test scores vary by ECD/non-ECD status

rsecdnec_test_by_ecd <- seda_oi_cov %>% 
  filter(subgroup == "ecd" | subgroup == "nec") %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rsecdnec, size = tot_asmts_mth)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "ECD/Non-ECD Relative Diversity Index",
       cex.axis = 1.5) +
  theme_bw() +
  facet_wrap(~subgroup) +
   guides(size = FALSE)

ggsave("rsecdnec_test_by_ecd.png")
```

```{r}
# racial diversity v. test score plot, overall with size as county size
rswhtblk_test_all <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhtblk, size = tot_asmts_mth)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "White-Black Relative Diversity Index",
       cex.axis = 1.5) +
  theme_bw() +
   guides(size = FALSE)

ggsave("rswhtblk_test_all.png")

# maybe don't need this 

hswhtblk_test_all <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= hswhtblk, size = tot_asmts_mth)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "White-Black Information Index",
       cex.axis = 1.5) +
  theme_bw() +
   guides(size = FALSE)

ggsave("hswhtblk_test_all.png")

rswhthsp_test_all <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhthsp, size = tot_asmts_mth)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "White-Hispanic Relative Diversity Index",
       cex.axis = 1.5) +
  theme_bw() +
   guides(size = FALSE)

ggsave("rswhthsp_test_all.png")

rsecdnec_test_all <- seda_oi_cov %>% 
  filter(subgroup == "all") %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rsecdnec, size = tot_asmts_mth)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "ECD/Non-ECD Relative Diversity Index",
       cex.axis = 1.5) +
  theme_bw() +
   guides(size = FALSE)

ggsave("rsecdnec_test_all.png")

# WB diversity v test score separated by race
rswhtblk_test_by_race <- seda_oi_cov %>% 
  filter(subgroup == "asn" | subgroup == "blk" | subgroup == "hsp" | subgroup == "wht") %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhtblk, size = tot_asmts_mth)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "White-Black Relative Diversity Index",
       cex.axis = 1.5) +
  theme_bw() +
  facet_wrap(~subgroup) +
   guides(size = FALSE)

ggsave("rswhtblk_test_by_race.png")

# same thing using Information Theory Index instead of Relative Diversity
hswhtblk_test_by_race <- seda_oi_cov %>% 
  filter(subgroup == "asn" | subgroup == "blk" | subgroup == "hsp" | subgroup == "wht") %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= hswhtblk, size = tot_asmts_mth)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "White-Black Information Index",
       cex.axis = 1.5) +
  theme_bw() +
  facet_wrap(~subgroup) +
   guides(size = FALSE)

ggsave("hswhtblk_test_by_race.png")

# WH diversity separated by race
rswhthsp_test_by_race <- seda_oi_cov %>% 
  filter(subgroup == "asn" | subgroup == "blk" | subgroup == "hsp" | subgroup == "wht") %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rswhthsp, size = tot_asmts_mth)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "White-Hispanic Relative Diversity Index",
       cex.axis = 1.5) +
  theme_bw() +
  facet_wrap(~subgroup) +
   guides(size = FALSE)

ggsave("rswhthsp_test_by_race.png")

# ECD diversity separated by race (already did it above so maybe take out)
rsecdnec_test_by_race <- seda_oi_cov %>% 
  filter(subgroup == "asn" | subgroup == "blk" | subgroup == "hsp" | subgroup == "wht") %>% 
  ggplot(aes(x=mn_avg_mth_eb, y= rsecdnec, size = tot_asmts_mth)) +
  geom_point(alpha=.25) + 
  geom_smooth(method=lm, se= TRUE) +
  labs(x = "Mean Standardized Math Score",
       y = "ECD/Non-ECD Relative Diversity Index",
       cex.axis = 1.5) +
  theme_bw() +
  facet_wrap(~subgroup) +
   guides(size = FALSE)

ggsave("rsecdnec_test_by_race.png")
```

```{r}
# don't need this chunk now that I have discovered sub-groups in the data
# and facet wrap takes care of sub-categories

# plots of school segregation on test scores by racial group (use seda_oi)

# Variables:
# rswhtblk
# rswhthsp
# rsecdnec
# 
# mn_wht
# mn_asn
# mn_blk
# mn_hsp
# mn_ecd
# mn_nec

rswhtblk_blk <- seda_scores_cov %>% 
  ggplot(aes(x=mn_blk, y= rswhtblk)) +
  geom_point(alpha=.5) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(title = "Black-White Segregation and Black Students' Scores",
       subtitle = "National Data on 3rd-8th graders, 2008-2016",
       caption = "Data from Opportunity Insights and Stanford Education Data Archive.",
       x = "Mean Standardized Score",
       y = "Relative Diversity Index") +
  theme_bw()  

rswhtblk_wht <- seda_scores_cov %>% 
  ggplot(aes(x=mn_wht, y= rswhtblk)) +
  geom_point(alpha=.5) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(title = "Black-White Segregation and White Students' Scores",
       subtitle = "National Data on 3rd-8th graders, 2008-2016",
       caption = "Data from Opportunity Insights and Stanford Education Data Archive.",
       x = "Mean Standardized Score",
       y = "Relative Diversity Index") +
  theme_bw() 

rswhtblk_comb_plot <- plot_grid(rswhtblk_blk, rswhtblk_wht)

# rswhtblk_blk_1 <- seda_scores_cov %>%
#   ggplot(aes(x=mn_blk, y= rswhtblk)) +
#   geom_point(alpha=.5) +
#   geom_smooth(method=lm, se= FALSE)
#
# rswhtblk_wht_1 <- seda_scores_cov %>%
#   ggplot(aes(x=mn_wht, y= rswhtblk)) +
#   geom_point(alpha=.5) +
#   geom_smooth(method=lm, se= FALSE)

# # --- test---
# plot_row <- plot_grid(rswhtblk_blk_1, rswhtblk_wht_1)
# 
# # now add the title
# title <- ggdraw() + 
#   draw_label(
#     "Black-White Segregation and Test Scores by Race",
#     fontface = 'bold',
#     x = 0,
#     hjust = 0
#   ) +
#   theme(
#     # add margin on the left of the drawing canvas,
#     # so title is aligned with left edge of first plot
#     plot.margin = margin(0, 0, 0, 7)
#   )
# x <-plot_grid(
#   title, plot_row,
#   ncol = 1,
#   # rel_heights values control vertical title margins
#   rel_heights = c(0.1, 1),
#   labels = c("Black Students", "White Students")
# )
# 
# 
# 
# title_theme <- ggdraw() +
#   draw_label("Socio-economic measures", 
#              fontfamily = theme_georgia()$text$family, 
#              fontface = theme_georgia()$plot.title$face, x = 0.05, hjust = 0)
# plot_grid(title_theme, gridded, ncol = 1, rel_heights = c(0.2, 1))


rswhthsp_hsp <- seda_scores_cov %>% 
  ggplot(aes(x=mn_hsp, y= rswhthsp)) +
  geom_point(alpha=.5) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(title = "Hispanic-White Segregation and Hispanic Students' Scores",
       subtitle = "National Data on 3rd-8th graders, 2008-2016",
       caption = "Data from Opportunity Insights and Stanford Education Data Archive.",
       x = "Mean Standardized Score",
       y = "Relative Diversity Index") +
  theme_bw() 


rswhthsp_wht <- seda_scores_cov %>% 
  ggplot(aes(x=mn_wht, y= rswhthsp)) +
  geom_point(alpha=.5) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(title = "Hispanic-White Segregation and White Students' Scores",
       subtitle = "National Data on 3rd-8th graders, 2008-2016",
       caption = "Data from Opportunity Insights and Stanford Education Data Archive.",
       x = "Mean Standardized Score",
       y = "Relative Diversity Index") +
  theme_bw()  

rswhthsp_wht <- seda_scores_cov %>% 
  ggplot(aes(x=mn_wht, y= rswhthsp)) +
  geom_point(alpha=.5) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(title = "Hispanic-White Segregation and White Students' Scores",
       subtitle = "National Data on 3rd-8th graders, 2008-2016",
       caption = "Data from Opportunity Insights and Stanford Education Data Archive.",
       x = "Mean Standardized Score",
       y = "Relative Diversity Index") +
  theme_bw()  

rsecdnec_ecd <- seda_scores_cov %>% 
  ggplot(aes(x=mn_ecd, y= rsecdnec)) +
  geom_point(alpha=.5) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(title = "ECD/Non-ECD Segregation and ECD Students' Scores",
       subtitle = "National Data on 3rd-8th graders, 2008-2016",
       caption = "Data from Opportunity Insights and Stanford Education Data Archive.",
       x = "Mean Standardized Score",
       y = "Relative Diversity Index") +
  theme_bw()  

rsecdnec_nec <- seda_scores_cov %>% 
  ggplot(aes(x=mn_nec, y= rsecdnec)) +
  geom_point(alpha=.5) + 
  geom_smooth(method=lm, se= FALSE) +
  labs(title = "ECD/Non-ECD Segregation and Non-ECD Students' Scores",
       subtitle = "National Data on 3rd-8th graders, 2008-2016",
       caption = "Data from Opportunity Insights and Stanford Education Data Archive.",
       x = "Mean Standardized Score",
       y = "Relative Diversity Index") +
  theme_bw()  

rsecdnec_comb_plot <- plot_grid(rsecdnec_ecd, rsecdnec_nec)

# maybe add in subsetting by income later?

```

```{r}
# regressions for intergenerational mobility and average learning rate

kfr_grd_math = lm(kfr_pooled_pooled_p25 ~ mn_grd_mth_ol + rswhtblk + rswhthsp + rsecdnec, data = seda_oi_cov)
kfr_grd_math_1 = lm(kfr_pooled_pooled_p25 ~ mn_grd_mth_ol + rswhtblk + rswhthsp + rsecdnec + sesavgall, data = seda_oi_cov)
kfr_grd_math_2 = lm(kfr_pooled_pooled_p25 ~ mn_grd_mth_ol + rswhtblk+ rswhthsp + rsecdnec + sesavgall + perblk + perhsp + perecd + sesavgwhtblk + sesavgwhthsp, data = seda_oi_cov)

# no matter which controls you add in, average learning rate (how much a grade
# learns over time) is still significant for intergenerational mobility

summary(kfr_grd_math)
summary(kfr_grd_math_1)

# do the same analyses for ELA

kfr_grd_ela = lm(kfr_pooled_pooled_p25 ~ mn_grd_ela_ol + rswhtblk +rswhthsp + rsecdnec, data = seda_oi_cov)
kfr_grd_ela_1 = lm(kfr_pooled_pooled_p25 ~ mn_grd_ela_ol + rswhtblk +rswhthsp + rsecdnec + sesavgall, data = seda_oi_cov)
kfr_grd_ela_2 = lm(kfr_pooled_pooled_p25 ~ mn_grd_ela_ol + rswhtblk +rswhthsp + rsecdnec + sesavgall + perblk + perhsp + perecd + sesavgwhtblk + sesavgwhthsp, data = seda_oi_cov)
  

# same results of significance for ELA

summary(kfr_grd_ela)
summary(kfr_grd_ela_1)

```

```{r}
# regression table for average learning rate results
stargazer(kfr_grd_math, kfr_grd_math_1, kfr_grd_math_2, kfr_grd_ela, kfr_grd_ela_1, kfr_grd_ela_2,
          type="html", 
          dep.var.labels=c("Intergenerational Mobility"),
          covariate.labels=c("County Grade Slope of Mean Achievement in Math", "County Grade Slope for Mean Achievement in ELA", "Relative Diversity index between schools: White/Black", "Relative Diversity index between schools: White/Hispanic", "Relative Diversity index between schools: Economically disadvantaged/Non ECD","SES Composite Score", "Percent Blacks in the Grade", "Percent Hispanic in the Grade", "Percent Economically Disadvantaged in the Grade", "White-Black Gap in SES Composite Score", "White-Hispanic Gap in SES Composite Score"),
          column.labels = c("Without Controls", "With SES Composite", "With Additional Controls", "Without Controls","With SES Composite", "With Additional Controls"), out="kfr_grd_math_ela.html")

```

```{r}
kfr_coh_math = lm(kfr_pooled_pooled_p25 ~ mn_coh_mth_ol + rswhtblk + rswhthsp + rsecdnec, data = seda_oi_cov)
kfr_coh_math_1 = lm(kfr_pooled_pooled_p25 ~ mn_coh_mth_ol + rswhtblk + rswhthsp + rsecdnec + sesavgall, data = seda_oi_cov)
kfr_coh_math_2 = lm(kfr_pooled_pooled_p25 ~ mn_coh_mth_ol + rswhtblk + rswhthsp + rsecdnec + sesavgall + perblk + perhsp + perecd + sesavgwhtblk + sesavgwhthsp, data = seda_oi_cov)

# improvement of scores for a school over time matters for intergen mobility

summary(kfr_coh_math)
summary(kfr_coh_math_1)

kfr_coh_ela = lm(kfr_pooled_pooled_p25 ~ mn_coh_ela_ol + rswhtblk + rswhthsp + rsecdnec, data = seda_oi_cov)
kfr_coh_ela_1 = lm(kfr_pooled_pooled_p25 ~ mn_coh_ela_ol + rswhtblk + rswhthsp + rsecdnec + sesavgall, data = seda_oi_cov)
kfr_coh_ela_2 = lm(kfr_pooled_pooled_p25 ~ mn_coh_ela_ol + rswhtblk + rswhthsp + rsecdnec + sesavgall + perblk + perhsp + perecd + sesavgwhtblk + sesavgwhthsp, data = seda_oi_cov)

# same results for ELA

summary(kfr_coh_ela)
summary(kfr_coh_ela_1)

```

```{r}
# regression table for trends in average test scores in the same grade

stargazer(kfr_coh_math, kfr_coh_math_1, kfr_coh_math_2, kfr_coh_ela, kfr_coh_ela_1, kfr_coh_ela_2,
          type="html", 
          dep.var.labels=c("Intergenerational Mobility"),
          covariate.labels=c("County Cohort Slope of Mean Achievement in Math", "County Cohort Slope of Mean Achievement in ELA", "Relative Diversity index between schools: White/Black", "Relative Diversity index between schools: White/Hispanic", "Relative Diversity index between schools: Economically disadvantaged/Non ECD","SES Composite Score", "Percent Blacks in the Grade", "Percent Hispanic in the Grade", "Percent Economically Disadvantaged in the Grade", "White-Black Gap in SES Composite Score", "White-Hispanic Gap in SES Composite Score"),
          column.labels = c("Without Controls", "With SES Composite", "With Additional Controls", "Without Controls","With SES Composite", "With Additional Controls"), out="kfr_coh_math_ela.html")
```

```{r}
# regressions on the correlations between diversity within school and scores 
# took out "sesavgall" and only included it in the regressions with controls 
div_score <- lm(mn_avg_mth_ol~ rswhtblk + rswhthsp + rsecdnec, data = seda_oi_cov)

# interesting that exposure to other ECD is not as important for math as it is
# for ELA
summary(div_score)

div_score_ela <-lm(mn_avg_ela_ol~ rswhtblk + rswhthsp + rsecdnec, data = seda_oi_cov)
summary(div_score_ela) 

# with controls added

div_score_cont <- lm(mn_avg_mth_ol~ rswhtblk + rswhthsp + rsecdnec + sesavgall + perblk + perhsp + perecd + sesavgwhtblk + sesavgwhthsp, data = seda_oi_cov)

summary(div_score_cont)

div_score_ela_cont <-lm(mn_avg_ela_ol~ rswhtblk + rswhthsp + rsecdnec + sesavgall+ perblk + perhsp + perecd + sesavgwhtblk + sesavgwhthsp, data = seda_oi_cov)

summary(div_score_ela_cont) 

```

```{r}
# regressions of diversity on test score by race
div_score_asn <- lm(mn_avg_mth_ol~ rswhtblk + rswhthsp + rsecdnec, data = (seda_oi_cov %>% filter(subgroup == "asn")))

div_score_blk <- lm(mn_avg_mth_ol~ rswhtblk + rswhthsp + rsecdnec, data = (seda_oi_cov %>% filter(subgroup == "blk")))

div_score_hsp <- lm(mn_avg_mth_ol~ rswhtblk + rswhthsp + rsecdnec, data = (seda_oi_cov %>% filter(subgroup == "hsp")))

div_score_wht <- lm(mn_avg_mth_ol~ rswhtblk + rswhthsp + rsecdnec, data = (seda_oi_cov %>% filter(subgroup == "wht")))

# with controls

div_score_asn_cont <- lm(mn_avg_mth_ol~ rswhtblk + rswhthsp + rsecdnec+ sesavgall + perblk + perhsp + perecd + sesavgwhtblk + sesavgwhthsp, data = (seda_oi_cov %>% filter(subgroup == "asn")))

div_score_blk_cont <- lm(mn_avg_mth_ol~ rswhtblk + rswhthsp + rsecdnec+ sesavgall + perblk + perhsp + perecd + sesavgwhtblk + sesavgwhthsp, data = (seda_oi_cov %>% filter(subgroup == "blk")))

div_score_hsp_cont <- lm(mn_avg_mth_ol~ rswhtblk + rswhthsp + rsecdnec+ sesavgall + perblk + perhsp + perecd + sesavgwhtblk + sesavgwhthsp, data = (seda_oi_cov %>% filter(subgroup == "hsp")))

div_score_wht_cont <- lm(mn_avg_mth_ol~ rswhtblk + rswhthsp + rsecdnec+ sesavgall + perblk + perhsp + perecd + sesavgwhtblk + sesavgwhthsp, data = (seda_oi_cov %>% filter(subgroup == "wht")))


```


```{r}
# regression table for math scores by diversity factors 

stargazer(div_score, div_score_cont, div_score_ela, div_score_ela_cont, 
          type="html", 
          dep.var.labels=c("Standardized Math Scores", "Standardized ELA Scores"),
          covariate.labels=c("Relative Diversity index between schools: White/Black", "Relative Diversity index between schools: White/Hispanic", "Relative Diversity index between schools: Economically disadvantaged/Non ECD","SES Composite Score", "Percent Blacks in the Grade", "Percent Hispanic in the Grade", "Percent Economically Disadvantaged in the Grade", "White-Black Gap in SES Composite Score", "White-Hispanic Gap in SES Composite Score"),
          column.labels = c("Without Controls", "With Controls", "Without Controls", "With Controls"), out="div_score_subject.html")

# table for diversity effects on math scores by race

stargazer(div_score_asn, div_score_asn_cont, div_score_blk, div_score_blk_cont, div_score_hsp, div_score_hsp_cont, div_score_wht, div_score_wht_cont,
          type="html", 
          dep.var.labels=c("Standardized Math Scores"),
          covariate.labels=c("Relative Diversity index between schools: White/Black", "Relative Diversity index between schools: White/Hispanic", "Relative Diversity index between schools: Economically disadvantaged/Non ECD","SES Composite Score", "Percent Blacks in the Grade", "Percent Hispanic in the Grade", "Percent Economically Disadvantaged in the Grade", "White-Black Gap in SES Composite Score", "White-Hispanic Gap in SES Composite Score"),
          column.labels = c("Asian, Without Controls", "Asian, With Controls", "Black, Without Controls", "Black, With Controls", "Hispanic, Without Controls", "Hispanic, With Controls", "White, Without Controls", "White, With Controls"), out="div_score_by_race.html")

```

